### ISSUE TITLE
:bomb: `Bug`: The configuration file key will crash the program if it is empty

### ISSUE THREAD

**Issue by linuxtmty** [devstream-io/devstream#606] opened 2022-05-25 07:43 UTC
### What Happened?

The configuration file key will crash the program if it is empty。
<img width="522" alt="image" src="https://user-images.githubusercontent.com/8682294/170206521-c6b4d985-6be1-44e4-92b7-8cf3ac24ece5.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8682294/170206695-363dc738-28d0-4acc-a74b-08d51edf27fe.png">

### How to Reproduce?

<img width="522" alt="image" src="https://user-images.githubusercontent.com/8682294/170206521-c6b4d985-6be1-44e4-92b7-8cf3ac24ece5.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8682294/170206695-363dc738-28d0-4acc-a74b-08d51edf27fe.png">

### Reason
config.go
<img width="736" alt="image" src="https://user-images.githubusercontent.com/8682294/170207567-7f0c98b7-985c-457c-9a09-d08efa7c73b8.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8682294/170207796-ee1654ad-cafa-42a0-a03f-524c527ecd3d.png">
The error returned by the configloader.LoadConf function is nil, but the init function judges that the error is not nil before doing error handling
### Solution
<img width="625" alt="image" src="https://user-images.githubusercontent.com/8682294/170208467-64b15d50-81b2-41c7-89b3-5daa13041ae6.png">
Returns the current first error

### DevStream Version

latest

**Comment by aFlyBird0** [comment] 2022-05-25 07:54
In fact, it involves more code that I have wanted to change for a long time.

I think the LoadConf function should return only `nil, error` or `non-nil-config, nil`.

That is, if the error returned is not nil, then the config returned should be trustworthy.

But in fact, as you suggest, the current `LoadConf` file also returns `nil, nil`. It's easy to confuse the caller.

There is a lot of this code in projects now.

https://github.com/devstream-io/devstream/blob/main/internal/pkg/pluginengine/cmd_apply.go#L15-L22

I think we should make `LoadConf` return `nil, error`, i.e. lines 20-22 are not necessary.

**Comment by aFlyBird0** [comment] 2022-05-25 07:56
@daniel-hutao this issue is related to #604 . Maybe you can focus on this issue, thanks!

**Comment by aFlyBird0** [comment] 2022-05-25 08:13
Sorry，I can;t reproduce this bug. 0.0.6 release and latest dev) @linuxtmty 

![image](https://user-images.githubusercontent.com/36830265/170214370-5ab04a11-ea95-40c5-a867-9f4c0dca1a2a.png)


![image](https://user-images.githubusercontent.com/36830265/170214329-96d58c41-4244-465a-86a3-a4ba4b68f773.png)

**Comment by daniel-hutao** [comment] 2022-05-26 02:26
I'm sorry I didn't give you feedback on this issue yesterday; it's something I've fixed in the `configloader` refactoring process. I haven't been able to merge it in time because of the refactoring and #596 support changes too many; thank you for your bug feedback, let's keep this issue open for now, and we'll come back to see if the issue is fixed after I finish refactoring.

**Comment by daniel-hutao** [comment] 2022-06-08 01:15
/close
fixed with #655

@linuxtmty I'm sorry, I had already started the refactoring of the `configloader` package before I saw this issue, but the work was blocked for some time, resulting in a little late merge.

Hope it didn't affect your passion!

**Closed by daniel-hutao** 2022-06-08 01:15 UTC
Labels: bug
